version: '3'

services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards
    ports:
      - 80:3000
    restart: unless-stopped
  influxdb:
    image: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=htlvb
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=htlvb
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped
  telegraf:
    image: telegraf
    environment:
      - SOLAR_API_HOST=10.174.27.14
      - WEATHER_LAT=48.0078587
      - WEATHER_LON=13.6460378
      - WEATHER_API_KEY=${OPEN_WEATHER_MAP_API_KEY}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
