apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    uid: a296b07c-64e6-47c9-9ea7-0963498b0b22
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: InfluxQL
      dbName: default
      timeInterval: '10s'
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $INFLUXDB_TOKEN'