{
 "title": "Default",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Energieverbrauch und -produktion",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "power_flow_realtime",
     "query": "SELECT \"site_watt_from_grid\"  / 100, \"site_watt_from_grid\" FROM \"power_flow_realtime\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "site_watt_surplus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "surplus" ], "type": "alias" }
      ],
      [
       { "params": [ "site_watt_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "generated" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energieeigenverbrauch",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "power_flow_realtime",
     "select": [
      [
       { "params": [ "site_self_consumption_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energieunabhängigkeit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "power_flow_realtime",
     "select": [
      [
       { "params": [ "site_autonomy_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_degrees" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bewölkung",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "cloudiness_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}